services:
  core:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./src/bentoml_data:/root/bentoml
      - ./src/fastapi_app:/app/fastapi_app
    networks:
      - novumquay-network

networks:
  novumquay-network:
    external: true